import { addIcons } from 'ionicons';
import { 
  heart, heartOutline, 
  settings, settingsOutline, 
  location, locationOutline,
  search, searchOutline,
  star, starOutline,
  thermometer, thermometerOutline,
  water, waterOutline,
  cloud, cloudOutline,
  time, timeOutline,
  navigate, navigateOutline,
  leaf, leafOutline,
  save, saveOutline,
  refresh, refreshOutline,
  code, codeOutline,
  send, sendOutline,
  chatbubble, chatbubbleOutline,
  arrowUp, arrowDown,
  speedometer, speedometerOutline,
  alertCircle, alertCircleOutline,
  home, homeOutline,
  add, addOutline,
  remove, removeOutline,
  trash, trashOutline,
  close, closeOutline, closeCircle, closeCircleOutline,
  menu, menuOutline,
  filter, filterOutline,
  sunny, sunnyOutline,
  rainy, rainyOutline,
  cloudyNight, cloudyNightOutline,
  partlySunny,
  informationCircle, informationCircleOutline,
  language, languageOutline
} from 'ionicons/icons';

// Registrar todos os ícones necessários
export function registerIcons() {
  addIcons({
    'heart': heart,
    'heart-outline': heartOutline,
    'settings': settings,
    'settings-outline': settingsOutline,
    'location': location,
    'location-outline': locationOutline,
    'search': search,
    'search-outline': searchOutline,
    'star': star,
    'star-outline': starOutline,
    'thermometer': thermometer,
    'thermometer-outline': thermometerOutline,
    'water': water,
    'water-outline': waterOutline,
    'cloud': cloud,
    'cloud-outline': cloudOutline,
    'time': time,
    'time-outline': timeOutline,
    'navigate': navigate,
    'navigate-outline': navigateOutline,
    'leaf': leaf,
    'leaf-outline': leafOutline,
    'save': save,
    'save-outline': saveOutline,
    'refresh': refresh,
    'refresh-outline': refreshOutline,
    'code': code,
    'code-outline': codeOutline,
    'send': send,
    'send-outline': sendOutline,
    'chatbubble': chatbubble,
    'chatbubble-outline': chatbubbleOutline,
    'arrow-up': arrowUp,
    'arrow-down': arrowDown,
    'speedometer': speedometer,
    'speedometer-outline': speedometerOutline,
    'alert-circle': alertCircle,
    'alert-circle-outline': alertCircleOutline,
    'home': home,
    'home-outline': homeOutline,
    'add': add,
    'add-outline': addOutline,
    'remove': remove,
    'remove-outline': removeOutline,
    'trash': trash,
    'trash-outline': trashOutline,
    'close': close,
    'close-outline': closeOutline,
    'close-circle': closeCircle,
    'close-circle-outline': closeCircleOutline,
    'menu': menu,
    'menu-outline': menuOutline,
    'filter': filter,
    'filter-outline': filterOutline,
    'sunny': sunny,
    'sunny-outline': sunnyOutline,
    'rainy': rainy,
    'rainy-outline': rainyOutline,
    'cloudy-night': cloudyNight,
    'cloudy-night-outline': cloudyNightOutline,
    'partly-sunny': partlySunny,
    'information-circle': informationCircle,
    'information-circle-outline': informationCircleOutline,
    'language': language,
    'language-outline': languageOutline,
  });
}